#!/usr/bin/env bash
# Render a reel, then lay a background-music bed under the scene's sound effects.
#
#   ./render.sh topics/monty_hall.py MontyHall            # final 1080x1350 + music
#   ./render.sh topics/monty_hall.py MontyHall preview    # fast 432x540 draft
#   MUSIC=my_track.mp3 ./render.sh ...                     # use your own track instead
#   MUSIC=none ./render.sh ...                             # no music (sfx only)
#   MUSIC_VOL=0.4 ./render.sh ...                          # music level (default 0.35)
#
# By default the music is generated by reelkit/audio.py to exactly fit the
# video, so it is royalty-free. The mix is loudness-normalised to -14 LUFS
# (the level Instagram/TikTok/YouTube play at). Output: out/<Scene>.mp4
set -euo pipefail
cd "$(dirname "$0")"

FILE=$1
SCENE=$2
MODE=${3:-final}
MANIM=${MANIM:-manim}
PY=${PY:-$(dirname "$(command -v "$MANIM")")/python}
[[ -x $PY ]] || PY=python3
MUSIC=${MUSIC:-auto}
MUSIC_VOL=${MUSIC_VOL:-0.35}

if [[ $MODE == preview ]]; then
  "$MANIM" -ql --resolution 432,540 "$FILE" "$SCENE"
  QDIR=540p15
else
  "$MANIM" -qh --resolution 1080,1350 --frame_rate 30 "$FILE" "$SCENE"
  QDIR=1350p30
fi

mkdir -p out
SRC="media/videos/$(basename "$FILE" .py)/$QDIR/$SCENE.mp4"
DST="out/$SCENE.mp4"
DUR=$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$SRC")

if [[ $MUSIC == none ]]; then
  cp "$SRC" "$DST"; echo "✓ $DST"; exit 0
fi
if [[ $MUSIC == auto ]]; then
  MUSIC="media/music_${SCENE}.wav"
  "$PY" -m reelkit.audio music "$DUR" "$MUSIC" >/dev/null
fi

FADE_AT=$("$PY" -c "print(max(0, $DUR - 2))")
MUSIC_CHAIN="[1:a]volume=${MUSIC_VOL},afade=t=out:st=${FADE_AT}:d=2[m]"
if ffprobe -v error -select_streams a -show_entries stream=index -of csv=p=0 "$SRC" | grep -q .; then
  # Scene already has sound effects: mix them over the music.
  FILTER="${MUSIC_CHAIN};[0:a][m]amix=inputs=2:duration=first:normalize=0,loudnorm=I=-14:TP=-1.5:LRA=11[a]"
else
  FILTER="${MUSIC_CHAIN};[m]loudnorm=I=-14:TP=-1.5:LRA=11[a]"
fi
ffmpeg -y -v error -i "$SRC" -stream_loop -1 -i "$MUSIC" -filter_complex "$FILTER" \
  -map 0:v -map "[a]" -c:v copy -c:a aac -b:a 192k -ar 48000 -t "$DUR" "$DST"
echo "✓ $DST"
